gnodeb:
  controlif:
    ip: "192.168.10.108"
    port: 9487
  dataif:
    ip: "192.168.10.108"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "95"
    tac: "00a000"
    gnbid: "000001"
  slicesupportlist:
    sst: "222"
    sd: "00007b"
  test: "normal-registration"

ue:
  msin: "0000000031"
  key: "0C0A34601D4F07677303652C0462535B"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  amf: "8000"
  sqn: "000000000000"
  dnn: "default"
  hplmn:
    mcc: "208"
    mnc: "95"
  snssai:
    sst: 222
    sd: "00007b"
  integrity:
    nia0: false
    nia1: false
    nia2: true
  ciphering:
    nea0: true
    nea1: false
    nea2: false
  test: "guti"

amfif:
  ip: "192.168.70.132"
  port: 38412
  name: "free5gc"
