gnodeb:
  gnbNum: 2
  controlif:
    ip: "172.22.0.254"
    port: 6000
  dataif:
    ip: "172.22.0.254"
    port: 2152
  plmnlist:
    mcc: "001"
    mnc: "01"
    tac: "000001"
    gnbid: "000051"
  slicesupportlist:
    sst: "01"
    # sd: "010203"

ue:
  ueNum: 10
  msin: "1000050009"
  key: "8baf473f2f8fd09487cccbd7097c6862"
  opc: "11111111111111111111111111111111"
  amf: "8000"
  sqn: "0000000"
  dnn: "internet"
  hplmn:
    mcc: "001"
    mnc: "01"
  snssai:
    sst: 1
    # sd: "010203"

amfif:
  ip: "172.22.0.10"
  port: 38412

tester:
  testernum: 2